// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO0svzxISVHBAK-6l4slPv4aXznKFUh_A',
    appId: '1:814752622487:web:92fc66d72777a47693c6d2',
    messagingSenderId: '814752622487',
    projectId: 'chat-app-1-6fd6d',
    authDomain: 'chat-app-1-6fd6d.firebaseapp.com',
    storageBucket: 'chat-app-1-6fd6d.firebasestorage.app',
    measurementId: 'G-E09LJ9S1DP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqmGYt79xNc__jE9J7MAuMTJhl3bTUohg',
    appId: '1:814752622487:android:63aaad26d8f92ba393c6d2',
    messagingSenderId: '814752622487',
    projectId: 'chat-app-1-6fd6d',
    storageBucket: 'chat-app-1-6fd6d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBocvGASOLSo5HVZdgGS_xkJAyV-npD6X4',
    appId: '1:814752622487:ios:71735b100761a1c493c6d2',
    messagingSenderId: '814752622487',
    projectId: 'chat-app-1-6fd6d',
    storageBucket: 'chat-app-1-6fd6d.firebasestorage.app',
    iosBundleId: 'com.example.chatApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBocvGASOLSo5HVZdgGS_xkJAyV-npD6X4',
    appId: '1:814752622487:ios:71735b100761a1c493c6d2',
    messagingSenderId: '814752622487',
    projectId: 'chat-app-1-6fd6d',
    storageBucket: 'chat-app-1-6fd6d.firebasestorage.app',
    iosBundleId: 'com.example.chatApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBO0svzxISVHBAK-6l4slPv4aXznKFUh_A',
    appId: '1:814752622487:web:51b680f67d57cf7393c6d2',
    messagingSenderId: '814752622487',
    projectId: 'chat-app-1-6fd6d',
    authDomain: 'chat-app-1-6fd6d.firebaseapp.com',
    storageBucket: 'chat-app-1-6fd6d.firebasestorage.app',
    measurementId: 'G-DDVKET7W2K',
  );
}
